10 counties:
Canada 
China 
France
Germany 
Italy 
Japan 
Netherlands
Singapore 
South Africa
Spain 

In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

1)The number of hospital beds per 1,000 people in the most recent reported year is in column 1.i.e.,age

This data is available in https://data.worldbank.org/indicator/SH.MED.BEDS.ZS

2)Percentage of persons over the age of 65 in the population is in column 2.i.e.,beds

This data is available in https://en.wikipedia.org/wiki/List_of_countries_by_age_structure 

3)The response variable for each country will be the number of COVID-19 deaths per 100K population is in column 3.i.e.,mortality_data

This information can be found at https://coronavirus.jhu.edu/data/mortality

Using pandas to read the .csv file as input and printing the input 

In [56]:
data = pd.read_csv("hw_3.csv");

In [57]:
df = pd.DataFrame(data)
df

beds  age   mortality_rate
0   25.20  17.0           26.90
1   43.10  10.6            0.34
2   59.10  19.7           51.56
3   80.00  21.5           12.10
4   31.40  23.0           61.57
5  129.80  27.0            1.35
6   31.70  18.8           41.09
7   24.86  12.9            0.50
8   23.00   5.3           32.79
9   29.70  19.4           74.38

Training the model using the above data for 10 different countries.

In [85]:
X=df.iloc[:,:-1].values  
y=df.iloc[:,-1:].values  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [86]:
X_train #output of trained data 

array([[ 31.4 ,  23.  ],
       [ 25.2 ,  17.  ],
       [ 80.  ,  21.5 ],
       [ 43.1 ,  10.6 ],
       [ 24.86,  12.9 ],
       [ 23.  ,   5.3 ],
       [129.8 ,  27.  ]])

In [87]:
print(X_test) #output of testing data 
print(y_test)

[[59.1 19.7]
 [29.7 19.4]
 [31.7 18.8]]
[[51.56]
 [74.38]
 [41.09]]


Using Linear Regression functions from sklearn package that is available at https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

In [88]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [89]:
r_sq = regressor.score(X_train, y_train)
r_sq

0.4785483870362931

In [90]:
ypred = regressor.predict(X_test)
print(ypred)
#pred_score = regressor.score(ypred, y_test)

[[21.5623426 ]
 [36.98022739]
 [34.53932679]]


In [91]:
print(y_test,"\n",ypred)

[[51.56]
 [74.38]
 [41.09]] 
 [[21.5623426 ]
 [36.98022739]
 [34.53932679]]


Applying the trained data to Predict number of deaths per 100k persons in USA with the data(age and available number of beds per 1000 people).

In [92]:
import numpy as np
usa = np.array([[2.9, 15.4]])
usa_pred = regressor.predict(usa)

In [93]:
print("Mortality rate for USA",usa_pred)

Mortality rate for USA [[42.67307807]]
